### ISSUE TITLE
[5] Serialise/Deserialise Protobuf and Bison (for MongoDB)

### ISSUE THREAD

**Issue by leopetter** [bptlab/cepta#158]
## Tasks
- [ ] Pull Request open 
- [ ] gain knowledge about different best practices
- [ ] generate a short presentation share you insights with the Team

## Acceptance Criteria
- [ ] Documented
- [ ] on Master
- [ ] Linter is okay
- [ ] Tests are written and green
- [ ] Code Review done
- [ ] Reviewed by PO

**Comment by romnn** [comment]
This is being worked on externally at [romnnn/bsonpb](https://github.com/romnnn/bsonpb).
